/** Master catalog of the 45 routes. Router and placeholder pages both read this. */
export const ALL_PAGE_META = [
  { id: 1, route: '/', title: 'Public landing', purpose: 'Explain the portal before asking anyone to sign up.', roles: 'public', file: 'public/LandingPage.jsx' },
  { id: 2, route: '/auth', title: 'Sign in / Sign up', purpose: 'Single sliding login and role-aware signup page.', roles: 'public', file: 'auth/AuthPage.jsx' },
  { id: 3, route: '/auth/forgot-password', title: 'Forgot password', purpose: 'Request a password reset link without leaking whether the email exists.', roles: 'public', file: 'auth/ForgotPasswordPage.jsx' },
  { id: 4, route: '/auth/reset-password/:token', title: 'Reset password', purpose: 'Set a new password from the emailed token.', roles: 'public', file: 'auth/ResetPasswordPage.jsx' },
  { id: 5, route: '/pending-approval', title: 'Account pending approval', purpose: 'Shown to inspectors awaiting admin verification.', roles: ['inspector'], file: 'auth/PendingApprovalPage.jsx', allowPendingInspector: true },
  { id: 6, route: '/404', title: 'Page not found', purpose: 'Standard not-found page.', roles: 'public', file: 'public/NotFoundPage.jsx' },
  { id: 7, route: '/offline', title: 'You are offline', purpose: 'PWA fallback when a route is not cached.', roles: 'public', file: 'public/OfflinePage.jsx' },
  { id: 8, route: '/scan', title: 'Scan a product', purpose: 'Upload or capture 1–4 label images and run a compliance scan.', roles: ['user', 'company', 'inspector'], file: 'scan/ScanPage.jsx' },
  { id: 9, route: '/scan/:id/result', title: 'Scan result', purpose: 'Field-by-field pass/fail/exempt/needs-review result.', roles: ['user', 'company', 'inspector'], file: 'scan/ScanResultPage.jsx' },
  { id: 10, route: '/scan/:id/report', title: 'Scan report', purpose: 'View and download PDF/DOCX compliance report.', roles: ['user', 'company', 'inspector'], file: 'scan/ScanReportPage.jsx' },
  { id: 11, route: '/history', title: 'Scan history', purpose: 'Own past scans, paginated and filterable.', roles: ['user', 'company', 'inspector'], file: 'shared/HistoryPage.jsx' },
  { id: 12, route: '/profile', title: 'Profile', purpose: 'Own account details and password change.', roles: ['user', 'company', 'inspector', 'admin'], file: 'shared/ProfilePage.jsx' },
  { id: 13, route: '/notifications', title: 'Notifications', purpose: 'Full in-app notification history.', roles: ['user', 'company', 'inspector', 'admin'], file: 'shared/NotificationsPage.jsx' },
  { id: 14, route: '/dashboard', title: 'Consumer dashboard', purpose: 'Scan CTA plus recent scans and complaints.', roles: ['user'], file: 'user/UserDashboardPage.jsx' },
  { id: 15, route: '/complaints/new/:scanId', title: 'File a complaint', purpose: 'Escalate a non-compliant scan toward enforcement.', roles: ['user'], file: 'user/NewComplaintPage.jsx' },
  { id: 16, route: '/complaints', title: 'My complaints', purpose: 'List of filed complaints with status stepper.', roles: ['user'], file: 'user/ComplaintsPage.jsx' },
  { id: 17, route: '/complaints/:id', title: 'Complaint detail', purpose: 'Single complaint timeline and resolution notes.', roles: ['user'], file: 'user/ComplaintDetailPage.jsx' },
  { id: 18, route: '/company/dashboard', title: 'Company dashboard', purpose: 'Last scanned products, compliance rate, scan CTA.', roles: ['company'], file: 'company/CompanyDashboardPage.jsx' },
  { id: 19, route: '/company/products', title: 'Company products', purpose: 'Paginated product list with last-scan status.', roles: ['company'], file: 'company/CompanyProductsPage.jsx' },
  { id: 20, route: '/company/products/:id/history', title: 'Product scan history', purpose: 'One product’s scan trend over time.', roles: ['company'], file: 'company/ProductHistoryPage.jsx' },
  { id: 21, route: '/company/team', title: 'Company team', purpose: 'Invite and manage staff logins under this company.', roles: ['company'], file: 'company/CompanyTeamPage.jsx' },
  { id: 22, route: '/company/profile', title: 'Company profile', purpose: 'Registration details. Registration number is read-only.', roles: ['company'], file: 'company/CompanyProfilePage.jsx' },
  { id: 23, route: '/inspector/dashboard', title: 'Inspector dashboard', purpose: 'Assigned complaints, risk-sorted companies, weekly stats.', roles: ['inspector'], file: 'inspector/InspectorDashboardPage.jsx' },
  { id: 24, route: '/inspector/scan', title: 'Field inspection scan', purpose: 'Scan flow plus GPS auto-tag and case formalization.', roles: ['inspector'], file: 'inspector/InspectorScanPage.jsx' },
  { id: 25, route: '/inspector/companies', title: 'Companies by risk', purpose: 'Full company list sorted by risk score descending.', roles: ['inspector'], file: 'inspector/InspectorCompaniesPage.jsx' },
  { id: 26, route: '/inspector/companies/:id/history', title: 'Company audit history', purpose: 'Every past scan and violation for one company.', roles: ['inspector'], file: 'inspector/CompanyAuditHistoryPage.jsx' },
  { id: 27, route: '/inspector/cases', title: 'My cases', purpose: 'Inspector cases filtered by draft / locked / resolved.', roles: ['inspector'], file: 'inspector/InspectorCasesPage.jsx' },
  { id: 28, route: '/inspector/cases/:id', title: 'Case detail', purpose: 'Evidence, lock case, append-only addendum.', roles: ['inspector'], file: 'inspector/CaseDetailPage.jsx' },
  { id: 29, route: '/inspector/complaints', title: 'Assigned complaints', purpose: 'Complaints assigned to this inspector with inline actions.', roles: ['inspector'], file: 'inspector/InspectorComplaintsPage.jsx' },
  { id: 30, route: '/inspector/map', title: 'Field map', purpose: 'High-risk companies and recent complaint locations.', roles: ['inspector'], file: 'inspector/InspectorMapPage.jsx' },
  { id: 31, route: '/inspector/offline-queue', title: 'Offline scan queue', purpose: 'IndexedDB queue of scans waiting to sync.', roles: ['inspector'], file: 'inspector/OfflineQueuePage.jsx' },
  { id: 32, route: '/inspector/profile', title: 'Inspector profile', purpose: 'Department, badge ID, and jurisdiction.', roles: ['inspector'], file: 'inspector/InspectorProfilePage.jsx' },
  { id: 33, route: '/admin/dashboard', title: 'Admin dashboard', purpose: 'Analytics: stats, charts, top-risk companies.', roles: ['admin'], file: 'admin/AdminDashboardPage.jsx' },
  { id: 34, route: '/admin/companies', title: 'All companies', purpose: 'Searchable/filterable company directory.', roles: ['admin'], file: 'admin/AdminCompaniesPage.jsx' },
  { id: 35, route: '/admin/companies/:id', title: 'Company record', purpose: 'Full profile, history, and risk-score override with reason.', roles: ['admin'], file: 'admin/AdminCompanyDetailPage.jsx' },
  { id: 36, route: '/admin/complaints', title: 'Complaint triage', purpose: 'Assign inspectors; oldest unassigned first.', roles: ['admin'], file: 'admin/AdminComplaintsPage.jsx' },
  { id: 37, route: '/admin/cases', title: 'All cases', purpose: 'Search cases across every inspector.', roles: ['admin'], file: 'admin/AdminCasesPage.jsx' },
  { id: 38, route: '/admin/inspectors', title: 'Inspectors', purpose: 'All inspectors with status and basic performance stats.', roles: ['admin'], file: 'admin/AdminInspectorsPage.jsx' },
  { id: 39, route: '/admin/inspectors/pending', title: 'Pending inspector approvals', purpose: 'Approve or reject inspector signups.', roles: ['admin'], file: 'admin/PendingInspectorsPage.jsx' },
  { id: 40, route: '/admin/inspectors/:id/performance', title: 'Inspector performance', purpose: 'Scans, cases closed, average time to resolution.', roles: ['admin'], file: 'admin/InspectorPerformancePage.jsx' },
  { id: 41, route: '/admin/rules', title: 'Rules management', purpose: 'View, add, and deactivate Legal Metrology rules.', roles: ['admin'], file: 'admin/AdminRulesPage.jsx' },
  { id: 42, route: '/admin/users', title: 'User accounts', purpose: 'Search, view, and deactivate user/company accounts.', roles: ['admin'], file: 'admin/AdminUsersPage.jsx' },
  { id: 43, route: '/admin/reports', title: 'Bulk reports', purpose: 'Date-range/region summary export as PDF or CSV.', roles: ['admin'], file: 'admin/AdminReportsPage.jsx' },
  { id: 44, route: '/admin/audit-log', title: 'Audit log', purpose: 'Who changed what and when — read-only accountability trail.', roles: ['admin'], file: 'admin/AdminAuditLogPage.jsx' },
  { id: 45, route: '/admin/profile', title: 'Admin profile', purpose: 'Administrator account settings.', roles: ['admin'], file: 'admin/AdminProfilePage.jsx' },
];
